### ISSUE TITLE
XML file updates don't work properly

### ISSUE THREAD

**Issue by Alagaros** [Dalthow/Launcher#3]
If this order is selected the launcher doesn't think there is an update available.
              
`
<update latest="false" version="0.1.0.0" branch="beta">
			<link>http://dalthow.com/share/downloads/software/etaron/Etaron%200.1.0.0.zip</link>
			<md5>
				<jar>db35111d79089b8e57eaacf61fffdbc0</jar>
				<zip>6ea4caeb996877054cd4171abe287293</zip>
			</md5>
		</update>
`

`
		<update latest="true" version="0.1.0.1" branch="beta">
			<link>http://dalthow.com/share/downloads/software/etaron/Etaron%200.1.0.1.zip</link>
			<md5>
				<jar>3810544dcd2a2b92ee25af37eae419b5</jar>
				<zip>de45ff724fb8048265771d680c4b1547</zip>
			</md5>
		</update>
`

If you swap the two around it does detect so its something with the order. If you can't look into it I will later :)

**Comment by Alagaros** [comment]
Well found out what it was, the selected-index has nothing to do with what it should grab. A fix would be to know on which index the latest version would be. 

`
if(GameUtils.getChecksum(tempFile.getAbsolutePath()).matches(Xml.getUpdates().get(Window.gameList.getSelectedIndex()).getZipMd5()))
`

**Comment by Alagaros** [comment]
Fixed!

`
// Returns the id of the latest update
	
	public static int getLatestId()
	{
		for(int i = 0; i < updates.values().size(); i++)
		{
			if(updates.get(i).isLatest())
			{
				return i;
			}
		}
		
		return 0;
	}
`

**Comment by Alagaros** [comment]
Well time to reopen this one, seems that it doesn't prompt a update if there are more then two.

**Comment by MattsMc** [comment]
Fixed i guess
